---
- name: To Install Httpd Service
  hosts: localhost
  become: true
  gather_facts: false
  use_backend=dnf 
  tasks:
  - name: install the latest version of Apache
    dnf:
    name: httpd
    state: latest
